[package]
name = "rustle"
version = "0.1.0"
edition = "2021"
authors = ["Abadyr"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
bracket-random = "0.8.7"